### ISSUE TITLE
[BUG] Not able to apply table styles using custom templates

### ISSUE THREAD

**Issue by sha-trix** [RossMurr4y/mdbook-docx#1]
## Current Behaviour
format given in template for tables are not applying in word document and default style is displayed

## Expected Behaviour
format given in template for tables should be displayed in word document

## Steps to Reproduce

1.
2.
3.
4.

**Comment by RossMurr4y** [comment]
Thanks for logging a bug ticket! 

This has bothered me as well, and it's not perfect but it can be done. It comes down to how Word document styles are defined for tables.

When editing your template docx file: 

1. select a Table (or create one) so the "Table Design" tab appears
2. select to expand the table styles list, and then "Modify Table Styles" at the bottom of the list
3. Locate the style simply called "Table" and edit this style in this window with your preferences. 
4. Save the template.

New documents produced from the template should use this style.

![image](https://github.com/RossMurr4y/mdbook-docx/assets/20530524/55ab3ad2-37b7-4e9c-87f9-8c9aa6f8ba1c)

![image](https://github.com/RossMurr4y/mdbook-docx/assets/20530524/8832f8b3-2008-413e-b892-007a26d65cac)
